%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo([
  {
    "Term_Years": 1,
    "CustomerID": "66265",
    "SumAssured": 221958,
    "Mobile": "5207382966",
    "AgentID": "44353",
    "InsurerID": "Metlife",
    "Type": "Health",
    "CustomerName": "GaUjugzk",
    "Address": "XXXXX",
    "Name": "Corona Policy - MetLife Medical Insurance",
    "Agency": "XXX",
    "InsurerName": "MetLife Medical Insurance",
    "AgentName": "cErDzrCs",
    "Premium": 15576,
    "PolicyDate": "2022-06-03",
    "MonthlyPremium_First_2_yrs": 15576,
    "MonthlyPremium_From_3rd_yrs": 15576,
    "Email": "LwxMtoaE20@gmail.com",
    "Status": "Active",
    "Claimed": "No"
  },
  {
    "Term_Years": 2,
    "CustomerID": "612",
    "SumAssured": 436392,
    "Mobile": "2888567361",
    "AgentID": "22852",
    "InsurerID": "Metlife",
    "Type": "Health",
    "CustomerName": "RygplEPs",
    "Address": "XXXXX",
    "Name": "Corona Policy - MetLife Medical Insurance",
    "Agency": "XXX",
    "InsurerName": "MetLife Medical Insurance",
    "AgentName": "CzIVFKPn",
    "Premium": 15312,
    "PolicyDate": "2022-06-03",
    "MonthlyPremium_First_2_yrs": 15312,
    "MonthlyPremium_From_3rd_yrs": 15312,
    "Email": "aqdNwNXV56@gmail.com",
    "Status": "Active",
    "Claimed": "No"
  },
  {
    "Term_Years": 3,
    "CustomerID": "40534",
    "SumAssured": 643302,
    "Mobile": "1108516928",
    "AgentID": "2931",
    "InsurerID": "Metlife",
    "Type": "Health",
    "CustomerName": "IVueKhfM",
    "Address": "XXXXX",
    "Name": "Corona Policy - MetLife Medical Insurance",
    "Agency": "XXX",
    "InsurerName": "MetLife Medical Insurance",
    "AgentName": "NQYVDMDm",
    "Premium": 15048,
    "PolicyDate": "2022-06-03",
    "MonthlyPremium_First_2_yrs": 15048,
    "MonthlyPremium_From_3rd_yrs": 15048,
    "Email": "RSWSeBLr88@gmail.com",
    "Status": "Active",
    "Claimed": "No"
  },
  {
    "Term_Years": 5,
    "CustomerID": "47381",
    "SumAssured": 1034550,
    "Mobile": "8020534531",
    "AgentID": "97135",
    "InsurerID": "Metlife",
    "Type": "Health",
    "CustomerName": "CqHRmcIR",
    "Address": "XXXXX",
    "Name": "Corona Policy - MetLife Medical Insurance",
    "Agency": "XXX",
    "InsurerName": "MetLife Medical Insurance",
    "AgentName": "AzKhtRSn",
    "Premium": 14520,
    "PolicyDate": "2022-06-03",
    "MonthlyPremium_First_2_yrs": 14520,
    "MonthlyPremium_From_3rd_yrs": 14520,
    "Email": "CDYRxefK65@gmail.com",
    "Status": "Active",
    "Claimed": "No"
  },
  {
    "Term_Years": 10,
    "CustomerID": "25935",
    "SumAssured": 1881000,
    "Mobile": "4673748118",
    "AgentID": "78106",
    "InsurerID": "Metlife",
    "Type": "Health",
    "CustomerName": "fHgYLZvQ",
    "Address": "XXXXX",
    "Name": "Corona Policy - MetLife Medical Insurance",
    "Agency": "XXX",
    "InsurerName": "MetLife Medical Insurance",
    "AgentName": "QLFqFfAr",
    "Premium": 13200,
    "PolicyDate": "2022-06-03",
    "MonthlyPremium_First_2_yrs": 13200,
    "MonthlyPremium_From_3rd_yrs": 13200,
    "Email": "ZFVSBDnW31@gmail.com",
    "Status": "Active",
    "Claimed": "No"
  },
  {
    "Term_Years": 15,
    "CustomerID": "24568",
    "SumAssured": 2539350,
    "Mobile": "3278511633",
    "AgentID": "9017",
    "InsurerID": "Metlife",
    "Type": "Health",
    "CustomerName": "WgLeVoqd",
    "Address": "XXXXX",
    "Name": "Corona Policy - MetLife Medical Insurance",
    "Agency": "XXX",
    "InsurerName": "MetLife Medical Insurance",
    "AgentName": "VewFXZOI",
    "Premium": 11880,
    "PolicyDate": "2022-06-03",
    "MonthlyPremium_First_2_yrs": 11880,
    "MonthlyPremium_From_3rd_yrs": 11880,
    "Email": "WYlJjwBj84@gmail.com",
    "Status": "Active",
    "Claimed": "No"
  }
])