request:
  host: "thirdparty-insuranceproviders.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/"
  client_id: "5d6552c38a854acba13f4155afaef89a"
  client_secret: "5825E991e0904C2CBB4097aE0D802f7E"
  contentType: "application/json"
  accept: "application/json"

https:
  host: "0.0.0.0"
  port: "8087"
  protocol: "HTTPS"
  basepath: "/"
  
keystore:
  client:
    path: "clientkeystore.jks"
    type: "JKS"
    alias: "myclient"
    keypassword: "password"
    password: "password"
  
  server:
    path: "serverkeystore.jks"
    type: "JKS"
    alias: "myserver"
    keypassword: "password"
    password: "password"
    


truststore:
  client:
    path: "clienttruststore.jks"
    type: "JKS"
    keypassword: "password"
  server:
    path: "servertruststore.jks"
    type: "JKS"
    keypassword: "password"
    

json:
  logger:
    application:
      name: "Insurance Application"
      version: "1.0.0"
      env: "Sandbox"

sfdc:
  username: "ravikumar.j.jayaraj@apisero.com"
  password: "Jarvis2@"
  token:  "mhTLDk3KT8XunCiLHZMXEKq3"
  
  
sqs:
  accessKey: "AKIA3W3YAXU5SO4SYZWQ"
  secretKey: "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"
  arn: "arn:aws:sqs:us-east-2:805021203771:health"
  url: "https://sqs.us-east-2.amazonaws.com/805021203771/health"
  region: "US East (Ohio)"