#%RAML 1.0 DataType
type: object

properties:
  Term_Months: integer
  CustomerID: string
  SumAssured: integer
  Mobile: string
  AgentID: string
  InsurerID: string
  Type: string
  CustomerName: string
  Address: string
  Name: string
  Agency: string
  InsurerName: string
  AgentName: string
  Premium: integer
  PolicyDate: string
  MonthlyPremium_First_2_yrs: integer
  MonthlyPremium_From_3rd_yrs: integer
  Email: string
  Status: string
  Claimed: string