{
  "Term_Years": 15,
  "CustomerID": "17046",
  "SumAssured": 2539350,
  "Mobile": "7987943738",
  "AgentID": "17060",
  "InsurerID": "Metlife",
  "Type": "Health",
  "CustomerName": "qdEqqFAv",
  "Address": "XXXXX",
  "Name": "Corona Policy - MetLife Medical Insurance",
  "Agency": "XXX",
  "InsurerName": "MetLife Medical Insurance",
  "AgentName": "TsIDIPFU",
  "Premium": 11880,
  "PolicyDate": "2022-06-01",
  "MonthlyPremium_First_2_yrs": 11880,
  "MonthlyPremium_From_3rd_yrs": 11880,
  "Email": "IXQgBGPC4@gmail.com",
  "Status": "Active",
  "Claimed": "No"
}